version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-api
    container_name: todo-api
    restart: always
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGODB_USER
      - MONGO_PASSWORD=$MONGODB_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGODB_LOCAL_PORT
      - MONGO_DB=$MONGODB_DATABASE
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  
    ports:
      - "$MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: